export enum Kinship {
  MOTHER = 'MOTHER',
  FATHER = 'FATHER',
  UNCLE = 'UNCLE',
  AUNT = 'AUNT',
  GRANDPARENT = 'GRANDPARENT',
  BROTHER = 'BROTHER',
  SISTER = 'SISTER',
  STEPPARENT = 'STEPPARENT',
  COUSIN = 'COUSIN',
  GUARDIAN = 'GUARDIAN',
  GODPARENT = 'GODPARENT',
  OTHER = 'OTHER',
}
